export class Mediafiliacion{
    public estatura: String;
    public complexion: String
    public peso: Number;
    public piel: String;
    public colorPiel: String;
    public cantidadCabello: String;
    public colorCabello: String;
    public formaCabello: String;
    public calvicie: String;
    public implantacion: String;
    public narizRaiz: String;
    public dorsoNariz: String;
    public anchoNariz: String;
    public baseNariz: String;
    public alturaNariz: String;
    public frenteTamano: String;
    public frenteInclinacion: String;
    public frenteAncho: String;
    public bocaAncho: String;
    public bocaComisuras: String;
    public labiosEspesor: String;
    public labiosAlturaNaso: String;
    public labiosProminencia: String;
    public ojoColor: String;
    public ojoForma: String;
    public ojoTamano: String;
    public cejasImplantacion: String;
    public cejasForma : String;
    public cejasTamano: String;
    public cara: String;
    public mentonTipo: String;
    public mentonForma:String;
    public mentonInclinacion:String;
    public orejaForma:String;
    public orejaHelixOriginal:String;
    public orejaHelixSuperior:String;
    public orejaHelixPosterior:String;
    public orejaHelixAdherencia:String;
    public lobuloContorno:String;
    public lobuloAdherencia:String;
    public lobuloParticularidad:String;
    public lobuloDimension: String;
    public sangreTipo: String;
    public sangreRH: String;
    public usaAnteojos: Boolean;
}